### PR TITLE
x component is in the x.tf or x-component/main.tf

### PR DESCRIPTION
**Pull request by amazingandyyy**
**Description**

- add shell script to ensure component is defined inside the correct `component.tf` file OR `parent-component/main.tf`

**Changes**

* feat(hooks): check component is defined inside the correct component file

🚀 PR created with [fotingo](https://github.com/tagoro9/fotingo)

### CODE REVIEW

**Comment by gopkri24** [comment]
Looks like it might be an outcome of [RFC-288](https://team-turo.atlassian.net/browse/RFC-288)

**Comment by amazingandyyy** [comment]
@gopkri24 might have some overlap, but this is codify our existing standard for domain infra

**Comment by amazingandyyy** [comment]
I think your proposal resultshould consider backward compatible to the existing standard

**Review by greenkiwi — CHANGES_REQUESTED** [review]
@amazingandyyy This seems too aggressive.   

Do we really want this? 

I could easily see a place where you had created a component in a directory

```
/systems/some-system/this-component/
```
And it would be really natural and probably _right_ to put the component in the `main.tf` directory.

Maybe the check is `ok in main, if in directory with component in it`?  Or maybe full path to file needs to have `component` in it?

**Comment by amazingandyyy** [comment]
@greenkiwi this script does [handle](https://github.com/open-turo/standards-terraform/pull/31/files#diff-a07c52c5c843f3f415ea030c93d2f9ba74c106369f3f3d4e8c4c713d31f6834aR28) `component/main.tf`, it's allowed

**Pull request closed without merging**
